#!/bin/bash

# Last update 2017/04/13

# get default's locale file
DEFLOCDIR="/usr/share/sparky/sparky-aptus-upgrade"
if [ "`cat /etc/default/locale | grep de_DE`" != "" ]; then
. $DEFLOCDIR/de
elif [ "`cat /etc/default/locale | grep es_AR`" != "" ]; then
. $DEFLOCDIR/es
elif [ "`cat /etc/default/locale | grep fr_FR`" != "" ]; then
. $DEFLOCDIR/fr
elif [ "`cat /etc/default/locale | grep it_IT`" != "" ]; then
. $DEFLOCDIR/it
elif [ "`cat /etc/default/locale | grep ja_JP`" != "" ]; then
. $DEFLOCDIR/ja
elif [ "`cat /etc/default/locale | grep pl_PL`" != "" ]; then
. $DEFLOCDIR/pl
elif [ "`cat /etc/default/locale | grep pt_BR`" != "" ]; then
. $DEFLOCDIR/pt_BR
elif [ "`cat /etc/default/locale | grep pt_PT`" != "" ]; then
. $DEFLOCDIR/pt_PT
elif [ "`cat /etc/default/locale | grep ru_RU`" != "" ]; then
. $DEFLOCDIR/ru
elif [ "`cat /etc/default/locale | grep sv_SE`" != "" ]; then
. $DEFLOCDIR/se
else
. $DEFLOCDIR/en
fi

testroot="`whoami`"

if [ "$testroot" != "root" ]
then
	/usr/bin/remsu $0 &
fi

DIALOG="yad --width 400"
DIALOG600="yad --width 600"
TITLE="--always-print-result --dialog-sep --window-icon=/usr/share/icons/sparky/upgrade/aptus-upgrade.png --image=/usr/share/icons/sparky/upgrade/aptus-upgrade.png --title="
TITLETEXT="$LOCAL1"
TEXT="--text="
NOBUTTONS="--no-buttons"

if [ -f /opt/sparky/sparky-xterm ]
then
. /opt/sparky/sparky-xterm
else
SPARKYXTERM="x-terminal-emulator"
fi

if [ -f /opt/sparky/sparky-editor ]; then
. /opt/sparky/sparky-editor
else
SPARKYEDITOR="gnome-text-editor"
fi

if [ "$1" = "upgradefull" ]
then
	$SPARKYXTERM -e "apt full-upgrade --no-install-recommends -y --force-yes"
	sleep 1
	$SPARKYXTERM -e "apt install -f"
	sleep 1
	### re-check is your system up-to-date ###
	/usr/bin/sparky-aptus-upgrade

elif [ "$1" = "changelog" ]
then
	$SPARKYEDITOR /tmp/aptus-upgrade/changelog
	sh /usr/lib/sparky-aptus-upgrade/upgrade-now

fi

exit 0
